Forwarder redesign
funcx-faas/funcx-forwarder pull request #4
Opened 2020-12-03 23:06 UTC by yadudoc

This PR contains a series of changes that re-architects the `funcx-forwarder` to support more endpoints scalably.

Here's a summary of changes:

* Dockerfile updated to use a wait_for_redis.py script to wait for redis before forwarder-service is started

* TaskQueue from the funcx-forwarder is used by the forwarder that uses the ZMQ stone-house pattern
  * This ensures the connections over the web are encrypted and safe
  * endpoint clients without the key cannot connect
  * [TODO] Need work to crosscheck client key upon registration
  * Any number of endpoints may connect to the same queues for tasks, results and commands

* A new `RedisPubSub` class is implemented, that uses a combination of Redis queues and pub-sub channels
  * This ensures messages are stored in a queue if there are no pub-sub subscribers
  * Rather than having to listen to multiple queues, you subscribe to topics which are made for each endpoint
  * When an idle endpoint connects, the queue is flushed into the pub-sub channel

* A create_certs utility added to create server certs for local testing.

2021-02-17 21:05 UTC, BenGalewsky commented on Dockerfile
> +RUN pip install "git+https://github.com/funcx-faas/funcX.git@forwarder_rearch_1#egg=funcx&subdirectory=funcx_sdk"
These should be moved to requirements.txt

2021-02-17 21:45 UTC, BenGalewsky requested changes
This is a major achievement and the forwarder is much friendlier now. Just made a bunch of style and readability comments along with some unused variables that PyCharm pointed out to me

2021-02-17 21:45 UTC, BenGalewsky commented on entrypoint.sh
> +cat <<EOF > wait_for_redis.py
Go ahead and put this in a script in the repo and copy it into the Docker image.

2021-02-17 21:45 UTC, BenGalewsky commented on entrypoint.sh
> +python3 wait_for_redis.py
Will the exit(-1) in the python script cause the bash script to exit?

2021-02-17 21:45 UTC, BenGalewsky commented on entrypoint.sh
> +# forwarder-service -a $ADVERTISED_FORWARDER_ADDRESS -p 8080 --redishost $REDIS_HOST --redisport $REDIS_PORT
Don't leave commented out code

2021-02-17 21:45 UTC, BenGalewsky commented on entrypoint.sh
> +    ADVERTISED_FORWARDER_ADDRESS=`wget http://169.254.169.254/latest/meta-data/public-ipv4; cat public-ipv4`
Maybe add a comment here or make the link-local address an env var?

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +            # self.redis_client.hset(f'task_{task.task_id}', kind, json.dumps(payload))
Why this commented out code?

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +                self.redis_client.publish(f'{self.task_channel_prefix}{endpoint_id}', task_id)
Could this use the `put` method?

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +        self.pubsub.subscribe(f'{self.task_channel_prefix}{endpoint_id}')
Looks like `f'{self.task_channel_prefix}{endpoint_id}'` is repeated a lot.. should there be a getter method that generates this from the endpoint_id?

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +            logger.exception("Uncaught exception")
Really Ok to fall through when this happens?

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +def test_client(ep=None):
Can these be moved out of this file? Into a test package?

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/taskqueue.py
> +        assert self.mode in ['client', 'server'], "Only two modes are supported: client, server"
Don't need both assert and the `else` statement below

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/taskqueue.py
> +        max_timeout : int
max_timeout is never used

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/forwarder.py
> +                 poll_period: int = 10):
poll_period is never referenced

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/forwarder.py
> +        if not os.path.exists(self.keys_dir) or not os.listdir(self.keys_dir):
There is key related stuff here and in `task queue` - it would be easier to understand if there was a single keys manager class that wrapped it all up

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/forwarder.py
> +        """  DEBUG : We will initially hack this with just one named endpoint `testing_ep1`
Can this go away?

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/forwarder.py
> +            # Receive endpoint registration messages. Only registration messages
This is a really long method - it would be easier to understand if the different operations were pulled out into private methods, and then the run method is just the orchestration between them

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/forwarder.py
> +        # TODO : THis timeout might become an issue
Help make the run method more concise, move these queue setup tasks into a private method

2021-02-17 21:45 UTC, BenGalewsky commented on funcx_forwarder/forwarder.py
> +    # fw.start()
No commented out code

2021-02-24 19:20 UTC, yadudoc commented on Dockerfile
> +RUN pip install "git+https://github.com/funcx-faas/funcX.git@forwarder_rearch_1#egg=funcx&subdirectory=funcx_sdk"
Done

2021-02-24 22:55 UTC, yadudoc commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +            # self.redis_client.hset(f'task_{task.task_id}', kind, json.dumps(payload))
This was the old mechanism. Removed.

2021-02-24 23:00 UTC, yadudoc commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +                self.redis_client.publish(f'{self.task_channel_prefix}{endpoint_id}', task_id)
redis_client doesn't have a `put` method. RedisPubSub is sort of wrapping together the pub-sub and queues. Here we try to publish, and if there aren't any subscribers we push that message onto the queue.

2021-02-25 01:44 UTC, yadudoc commented on funcx_forwarder/forwarder.py
> +        """  DEBUG : We will initially hack this with just one named endpoint `testing_ep1`
Removed.

2021-02-25 01:54 UTC, yadudoc commented on entrypoint.sh
> +python3 wait_for_redis.py
I've added a `set -ex` to the top, that will cause the bash script to exist and show a meaningful error state over `kubectl`

2021-02-25 01:59 UTC, yadudoc commented on funcx_forwarder/forwarder.py
> +                 poll_period: int = 10):
Removed. I've also updated the doc strings to actually match the args.

2021-02-25 05:08 UTC, yadudoc commented on funcx_forwarder/forwarder.py
> +    # fw.start()
Done

2021-02-25 05:11 UTC, yadudoc commented on funcx_forwarder/forwarder.py
> +            # Receive endpoint registration messages. Only registration messages
I've split the 3 key steps in the main loop into more manageable methods: 
* `_handle_endpoint_registration()`
* `_forward_task_to_endpoint()`
* `_handle_results()`

2021-02-25 06:16 UTC, yadudoc commented on funcx_forwarder/forwarder.py
> +        # TODO : THis timeout might become an issue
done

2021-02-25 07:07 UTC, yadudoc commented on funcx_forwarder/forwarder.py
> +        if not os.path.exists(self.keys_dir) or not os.listdir(self.keys_dir):
I agree, but I think we are better off deferring this to the next round. What do you think?

2021-02-25 07:09 UTC, yadudoc commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +        self.pubsub.subscribe(f'{self.task_channel_prefix}{endpoint_id}')
Done

2021-02-25 07:10 UTC, yadudoc commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +            logger.exception("Uncaught exception")
Definitely not :) Fixed.

2021-02-25 07:19 UTC, yadudoc commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +def test_client(ep=None):
Done

2021-02-25 07:20 UTC, yadudoc commented on funcx_forwarder/taskqueue.py
> +        assert self.mode in ['client', 'server'], "Only two modes are supported: client, server"
Removed assertion.

2021-02-25 16:40 UTC, yadudoc commented on entrypoint.sh
> +    ADVERTISED_FORWARDER_ADDRESS=`wget http://169.254.169.254/latest/meta-data/public-ipv4; cat public-ipv4`
I've added a comment here.

2021-02-25 23:28 UTC, yadudoc commented
@BenGalewsky I've resolved most of the items you noted, but there are a couple that I think might be better to defer. Could you take a quick look, please?

2021-02-26 20:48 UTC, BenGalewsky commented on Dockerfile
> +# USER funcx
This works for me when I uncomment this line

2021-02-26 20:51 UTC, BenGalewsky commented on .github/workflows/ci.yaml
> +    # Add this back once done with testing and Tornado dep is resolved.
I just tried this out, but don't get any errors from safety check - perhaps we've merged the fixes into funcx repo?

2021-02-26 20:58 UTC, BenGalewsky commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +        self.pubsub = self.redis_client.pubsub()
Set `self.pubsub = None` in constructor method - Instance attribute pubsub should not be defined outside __init__

2021-02-26 20:59 UTC, BenGalewsky requested changes
Just a couple of things in the Dockerfile and the CI job that seem to be working and should be put back in.

Also a style issue I missed in redis_pubsub.py -- all instance attributes should be defined in the constructor.

Thank you!

2021-02-26 21:26 UTC, yadudoc commented on .github/workflows/ci.yaml
> +    # Add this back once done with testing and Tornado dep is resolved.
I've turned this back on. Those fixes are on this branch.

2021-02-26 21:28 UTC, yadudoc commented on funcx_forwarder/queues/redis/redis_pubsub.py
> +        self.pubsub = self.redis_client.pubsub()
Fixed.

2021-02-26 21:40 UTC, yadudoc commented on Dockerfile
> +# USER funcx
I should've given you more info on this. The container does build, but when helm launches the deployment, the forwarder fails with this :

```
2021-02-26 21:38:30 forwarder:133 [INFO]  Keys dir empty: /home/funcx/.curve, creating keys
Traceback (most recent call last):
  File "/usr/local/bin/forwarder-service", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/funcx_forwarder/service.py", line 198, in cli
    redis_port=args.redisport)
  File "/usr/local/lib/python3.7/site-packages/funcx_forwarder/forwarder.py", line 134, in __init__
    os.makedirs(self.keys_dir, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/funcx/.curve'
```

2021-03-02 17:35 UTC, yadudoc commented on Dockerfile
> +# USER funcx
Perhaps, we should fix this in a separate PR?

2021-03-02 20:33 UTC, yadudoc commented
Folks, I'm thinking of merging this soon if there are no objections. Pretty much all of @BenGalewsky 's comments have been addressed, and a couple of items are better off deferred to the next round of dev. Last call to @ryanchard, @ZhuozhaoLi, @joshbryan-globus before this :steam_locomotive:  goes into `main`.

2021-03-02 20:35 UTC, BenGalewsky commented on funcx_forwarder/forwarder.py
> +        if not os.path.exists(self.keys_dir) or not os.listdir(self.keys_dir):
Fine by me

2021-03-02 20:42 UTC, BenGalewsky commented on Dockerfile
> +# USER funcx
Should be easy to fix, but I would need to do more set up. Agreed, let's let it ride for now

2021-03-02 20:42 UTC, BenGalewsky approved these changes
Thanks for bringing us home. @yadudoc

2021-03-02 20:44 UTC, yadudoc commented
Choo Choo!

2021-03-02 20:44 UTC, merged